var url = decodeURIComponent(document.URL+"")+"";
var lang = url.split("?.")[2];
var javakw = ["java"];
var cppkw = ["cpp", "c++"];
var pykw = ["py", "python"];
var jskw = ["js", "javascript"];
var rbkw = ["rb", "ruby"];
var swiftkw = ["swift", "sft", "sw"];
var truthkw = ['tr', 'truth'];
